"""Reproduce the current five-figure IEEE TII figure package safely.

The publication package has several independently owned assets.  This entry
point owns only the frozen benchmark mission figure.  Figure 1 is delegated
to its scoped generator, Figure 2 and the walkthrough are preserved, and
Figure 3 is verified from its Draw.io source and renderer provenance rather
than regenerated from an obsolete layout.

Run from the repository root (matplotlib, numpy, Pillow, PyMuPDF and fonts)::

    python paper/tii/SUBMISSION-IEEE-TII/figures/make_publication_figures.py

Regenerate Figure 1 and the mission only, then validate all five and refresh
aggregate metadata. Figure 3 must already have a current export receipt.
To finalize metadata without invoking ANY figure generator::

    python paper/tii/SUBMISSION-IEEE-TII/figures/make_publication_figures.py --refresh-metadata

Use --verify-only for read-only validation of the assets and stored metadata.
It can be combined with --refresh-metadata to refresh metadata after validation.

Figure 3 has no checked-in export script.  Use ``--export-fig3`` to print the
explicit export hand-off instructions; the default path never silently
recreates a stale Figure 3.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import runpy
import sys
import xml.etree.ElementTree as ET
from pathlib import Path, PureWindowsPath

import fitz
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, __version__ as pillow_version
from matplotlib import font_manager

OUT = Path(__file__).resolve().parent
ROOT = OUT.parents[3]

ARCHIVE = "20260920094610-to4"
SOURCES = {
    f"bench/results/{ARCHIVE}/run.json":
        "c522578672d83f63236ac651f379247236f025b6cab8e8db421cb6e117fc1926",
    f"bench/results/{ARCHIVE}/agentteam-biax.log":
        "d38b1fc7e01689b6e99a460770104dbbd7175cfa8b4c45ba65256acd4d0eaf0a",
}

# Current manuscript assets.  Only the mission PDF/QA proof are generated by
# this module; the other entries are ownership and provenance declarations.
FIGURES = {
    "fig1-supervisory-binding": ("publication/fig1-supervisory-binding.pdf", (7.16, 2.72)),
    "fig2-architecture": ("publication/fig2-architecture.pdf", (7.1267, 2.5567)),
    "fig3-governed-supervisory-workflow": (
        "publication/fig3-governed-supervisory-workflow.pdf", (7.16, 3.50)),
    "fig-operational-walkthrough": ("walkthrough/fig-operational-walkthrough.pdf", (7.16, 3.40)),
    "fig-agentteam-mission": ("tii-final/fig-agentteam-mission.pdf", (7.16, 2.95)),
}
FIG1_GENERATOR = OUT / "publication/make_fig1.py"
FIG1_QA = OUT / "publication/fig1-supervisory-binding-qa.json"
FIG1_OUTPUTS = {
    OUT / "publication/fig1-supervisory-binding.pdf",
    OUT / "publication/fig1-supervisory-binding.svg",
    OUT / "publication/fig1-supervisory-binding.png",
    OUT / "publication/fig1-supervisory-binding-grayscale.png",
    OUT / "publication/fig1-supervisory-binding-qa.json",
}
FIG3_SOURCE = "paper/tii/SUBMISSION-IEEE-TII/figures/drawio/fig3-governed-supervisory-workflow.drawio"
FIG3_OUTPUT = "paper/tii/SUBMISSION-IEEE-TII/figures/publication/fig3-governed-supervisory-workflow.pdf"
FIG3_QA = OUT / "publication/fig3-governed-supervisory-workflow-qa.json"
WALKTHROUGH_PROVENANCE = OUT / "walkthrough/walkthrough-provenance.json"
MISSION_OUTPUTS = {OUT / "tii-final/fig-agentteam-mission.pdf", OUT / "tii-final/fig-agentteam-mission.png"}
PRESERVED_ASSETS = {
    "publication/fig2-architecture.pdf": "f57e93bfa6bb54cc0909746eeb978298d5432ad30f92fd853a581e5776cc0267",
    "drawio/fig2-architecture.drawio": "9cabeaf29e2f99d9cd90b3b1c645c78d3f8c400e5071d5082a0ed6545af638ef",
}
EXTRA_OUTPUTS = {
    "fig1-supervisory-binding": ["publication/fig1-supervisory-binding.svg",
                                "publication/fig1-supervisory-binding.png",
                                "publication/fig1-supervisory-binding-grayscale.png"],
    "fig2-architecture": [],
    "fig3-governed-supervisory-workflow": ["publication/fig3-governed-supervisory-workflow.svg",
                                         "publication/fig3-governed-supervisory-workflow.png"],
    "fig-operational-walkthrough": ["walkthrough/fig-operational-walkthrough.png",
                                    *[f"walkthrough/ui-crop-{i}.png" for i in range(1, 5)]],
    "fig-agentteam-mission": ["tii-final/fig-agentteam-mission.png"],
}

INK, BLUE, RULE, PALE = "#222222", "#466176", "#a9b1b8", "#f3f5f6"
KNOBS = {
    "cast-spd-sp": ("Casting speed", "m/min", "Modbus TCP"),
    "fast-roll-sp": ("MDO fast roll", "m/min", "Modbus TCP"),
    "rail-out-sp": ("TDO outlet width", "mm", "OPC UA"),
}


def sha256(path: Path | str) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_mission():
    for name, expected in SOURCES.items():
        if sha256(ROOT / name) != expected:
            raise ValueError(f"Frozen B source hash mismatch: {name}")
    run = json.loads((ROOT / next(iter(SOURCES))).read_text(encoding="utf-8-sig"))
    env = run["env"]
    if not (env["runId"] == ARCHIVE and env["profile"] == "integrated"
            and env["verdict"]["ok"]):
        raise ValueError("Expected the governing integrated B archive")
    mission = env["biax"]["missionTraj"]
    if [row["iter"] for row in mission] != list(range(5)):
        raise ValueError("Expected baseline and four archived intervention indices")
    log = (ROOT / f"bench/results/{ARCHIVE}/agentteam-biax.log").read_text(encoding="utf-8-sig")
    if log.count("judge=keep") != 4 or "terminal=COMPLETED" not in log:
        raise ValueError("Mission outcome annotations no longer match the trace")
    return env, mission


def configure():
    font_manager.findfont("Times New Roman", fallback_to_default=False)
    plt.rcParams.update({
        "font.family": "Times New Roman", "font.size": 8,
        "axes.labelsize": 8, "xtick.labelsize": 8, "ytick.labelsize": 8,
        "text.color": INK, "axes.labelcolor": INK, "axes.linewidth": 0.6,
        "pdf.fonttype": 42, "ps.fonttype": 42, "hatch.linewidth": 0.35,
    })


def canvas(name):
    _, (width, height) = FIGURES[name]
    fig = plt.figure(figsize=(width, height))
    ax = fig.add_axes([0, 0, 1, 1], xlim=(0, width), ylim=(0, height))
    ax.axis("off")
    return fig, ax


def label(ax, x, y, text, **kwargs):
    return ax.text(x, y, text, fontsize=kwargs.pop("fontsize", 8.5),
                   ha=kwargs.pop("ha", "left"), va="center", **kwargs)


def mission_figure(mission):
    fig, panel = canvas("fig-agentteam-mission")
    label(panel, 0.14, 2.77, "(a) Archived thickness observations", fontsize=9, fontweight="bold")
    label(panel, 3.55, 2.77, "(b) Governed-write ledger", fontsize=9, fontweight="bold")
    label(panel, 0.56, 2.52, "Hatched band: target 25.0 ± 0.7 μm", fontsize=8)
    ax = fig.add_axes([0.56 / 7.16, 0.73 / 2.95, 2.63 / 7.16, 1.64 / 2.95])
    ax.axhspan(24.3, 25.7, facecolor="white", edgecolor=RULE,
               linewidth=0.5, hatch="////", zorder=0)
    ax.axhline(25.0, color=BLUE, linewidth=0.65, linestyle="--", zorder=1)
    x = [row["iter"] for row in mission]
    h = [row["thickness"] for row in mission]
    ax.plot(x, h, linestyle="none", marker="o", markersize=4.8,
            markerfacecolor="white", markeredgecolor=INK, markeredgewidth=0.8, zorder=3)
    for xi, hi in zip(x, h):
        ax.annotate(f"{hi:.2f}", (xi, hi), xytext=(0, 12 if xi == x[-1] else 7),
                    textcoords="offset points", ha="center", fontsize=8)
    ax.set(xlim=(-0.45, 4.50), ylim=(24.1, 27.5), xticks=x,
           yticks=[24.5, 25.5, 26.5], xlabel="Governed write index (0 = baseline)",
           ylabel="Thickness (μm)")
    ax.tick_params(direction="in", top=True, right=True, width=0.6, length=3)
    left, right = 3.55, 7.03
    for xpos, text in ((left, "Write"), (3.94, "Parameter / setpoint change"), (6.26, "Transport")):
        label(panel, xpos, 2.42, text, fontsize=8, fontweight="bold")
    panel.plot([left, right], [2.28, 2.28], color=INK, linewidth=0.6)
    for row, y in zip(mission[1:], (2.04, 1.65, 1.26, 0.87)):
        parameter, unit, transport = KNOBS[row["knob"]]
        label(panel, left + 0.12, y, str(row["iter"]), fontsize=8, ha="center")
        label(panel, 3.94, y + 0.075, parameter, fontsize=8)
        label(panel, 3.94, y - 0.075,
              f"{row['from']:.1f} → {row['to']:.1f} {unit}", fontsize=8)
        label(panel, 6.26, y, transport, fontsize=8)
        panel.plot([left, right], [y - 0.19, y - 0.19], color=RULE, linewidth=0.4)
    label(panel, left, 0.47, "4 records; logged keep; parent COMPLETED.", fontsize=8)
    label(panel, 0.14, 0.13,
          "Frozen B; simulated plant; scripted policy. Markers are returned-bucket means, not a continuous trajectory.",
          fontsize=8)
    return fig


def figure_paths(name):
    if name != "fig-agentteam-mission":
        raise ValueError(f"Only the mission figure is generated here: {name}")
    pdf = OUT / FIGURES[name][0]
    return pdf, pdf.with_suffix(".png")


def check_pdf(name):
    """Inspect an existing PDF without writing to any owner's outputs."""
    relative, size = FIGURES[name]
    with fitz.open(OUT / relative) as doc:
        if len(doc) != 1:
            raise ValueError(f"Expected single-page figure: {name}")
        page = doc[0]
        spans = [s for b in page.get_text("dict")["blocks"] if "lines" in b
                 for line in b["lines"] for s in line["spans"] if s["text"].strip()]
        fonts = page.get_fonts(full=True)
        # Font extents can exceed actual ink (including multiline headings).
        # Record metric intersections for review, not as proof of visual overlap.
        overlaps = []
        for i, first in enumerate(spans):
            for second in spans[i + 1:]:
                intersection = fitz.Rect(first["bbox"]) & fitz.Rect(second["bbox"])
                if intersection.width > 0.75 and intersection.height > 0.75:
                    overlaps.append([first["text"], second["text"]])
        # The preserved Chromium architecture PDF has a 0.03 pt metric overhang.
        bounds = page.rect + (-0.05, -0.05, 0.05, 0.05)
        outside = [s["text"] for s in spans if not bounds.contains(fitz.Rect(s["bbox"]))]
        minimum = min((s["size"] for s in spans), default=0)
        info = {
            "size_in": [round(page.rect.width / 72, 4), round(page.rect.height / 72, 4)],
            "raster_images_in_pdf": len(page.get_image_info()),
            "embedded_fonts": bool(fonts) and all(bool(doc.extract_font(f[0])[3]) for f in fonts),
            "fonts": sorted({f[3] for f in fonts}),
            "minimum_font_pt": round(minimum, 4),
            "minimum_annotation_font_pt": round(minimum, 4),
            "text_spans": len(spans), "spans_outside_canvas": outside,
            "font_metric_overlap_pairs": overlaps,
            "font_metric_note": "Metric boxes are not glyph-ink bounds; visual review is separate.",
            "canvas_tolerance_pt": 0.05,
            "author_metadata": doc.metadata.get("author", ""),
            "raster_policy": ("Authentic screenshot crops; 8 pt minimum applies to vector annotations, not source UI pixels."
                              if name == "fig-operational-walkthrough" else "Vector only."),
        }
        if (info["size_in"] != list(size)
                or (info["raster_images_in_pdf"] and name != "fig-operational-walkthrough")
                or not info["embedded_fonts"] or minimum < 8 - 1e-4
                or outside or info["author_metadata"]):
            raise ValueError(f"Figure QA failed for {name}: {info}")
        return info


def save_and_check(fig, name):
    pdf, proof = figure_paths(name)
    pdf.parent.mkdir(parents=True, exist_ok=True)
    try:
        fig.savefig(pdf, metadata={"Creator": "Matplotlib publication figure generator",
                                   "Author": None, "CreationDate": None, "ModDate": None},
                    facecolor="white")
    finally:
        plt.close(fig)
    info = check_pdf(name)
    if info["font_metric_overlap_pairs"]:
        raise ValueError(f"Mission text overlaps: {info['font_metric_overlap_pairs']}")
    with fitz.open(pdf) as doc:
        doc[0].get_pixmap(dpi=300, alpha=False).save(proof)
    info["proof_dpi"] = 300
    return info


def _xml_cells(source: Path):
    cells = list(ET.parse(source).getroot().iter("mxCell"))
    ids = [cell.get("id") for cell in cells]
    if not cells or len(ids) != len(set(ids)):
        raise ValueError("Figure 3 requires native XML cells with unique ids")
    vertices = {cell.get("id") for cell in cells if cell.get("vertex") == "1"}
    edges = [cell for cell in cells if cell.get("edge") == "1"]
    icon_slots = [cell for cell in cells if cell.get("iconPlaceholder") == "true"]
    invalid_edges = [cell.get("id") for cell in edges
                     if cell.get("source") not in vertices or cell.get("target") not in vertices]
    cards = {cell.get("id") for cell in cells if cell.get("role") == "card"}
    if not cards or {slot.get("id") for slot in icon_slots} != {f"{card}-icon-slot" for card in cards}:
        raise ValueError("Figure 3 requires one named blank icon slot per card")
    for slot in icon_slots:
        geometry = slot.find("mxGeometry")
        if (slot.get("parent") not in ids or slot.get("value", "").strip() or geometry is None
                or float(geometry.get("width", "0")) <= 0 or float(geometry.get("height", "0")) <= 0):
            raise ValueError(f"Invalid blank icon slot: {slot.get('id')}")
    return cells, edges, icon_slots, invalid_edges


def verify_fig3_provenance():
    """Match current XML and every export to the renderer's hash receipt.

    This checks the owner's recorded provenance and PDF text against XML; it
    does not claim an independent geometry rerender without an exporter.
    """
    source, output = ROOT / FIG3_SOURCE, ROOT / FIG3_OUTPUT
    if not source.is_file() or not output.is_file() or not FIG3_QA.is_file():
        raise ValueError("Figure 3 XML, PDF, and QA provenance files are required; use --export-fig3")
    cells, edges, icon_slots, invalid_edges = _xml_cells(source)
    if invalid_edges:
        raise ValueError(f"Figure 3 has unresolved source/target ids: {invalid_edges}")
    qa = json.loads(FIG3_QA.read_text(encoding="utf-8"))
    # Owner receipts may contain Windows absolute paths even on another host.
    records = {PureWindowsPath(record["submission"]).name: record["sha256"]
               for record in qa.get("files", [])}
    for path in [source, output, output.with_suffix(".svg"), output.with_suffix(".png")]:
        if not path.is_file() or records.get(path.name) != sha256(path):
            raise ValueError(f"Figure 3 renderer provenance hash mismatch: {path.name}; use --export-fig3")
    expected = {"native_drawio_cells": len(cells), "native_connectors": len(edges), "icon_slots": len(icon_slots)}
    if (qa.get("xml_native_cells", qa.get("native_drawio_cells")) != len(cells)
            or qa.get("native_connectors") != len(edges)
            or ("icon_slots" in qa and qa["icon_slots"] != len(icon_slots))):
        raise ValueError(f"Figure 3 XML/PDF cell counts drifted: expected {expected}")
    info = check_pdf("fig3-governed-supervisory-workflow")
    with fitz.open(output) as doc:
        text = " ".join(doc[0].get_text().split())
    missing = [cell.get("id") for cell in cells
               if " ".join(cell.get("value", "").split()) not in text]
    if missing:
        raise ValueError(f"Figure 3 PDF is missing current XML labels: {missing}")
    if (qa.get("pdf_raster_images") != info["raster_images_in_pdf"]
            or qa.get("layout_issues", qa.get("measured_layout_issues"))
            or qa.get("minimum_pdf_font_pt", 0) < 8):
        raise ValueError("Figure 3 renderer QA does not satisfy vector/font requirements")
    return {"source_sha256": sha256(source), "output_sha256": sha256(output), **expected,
            "minimum_pdf_font_pt": info["minimum_font_pt"],
            "verification": "Owner export receipt hashes and current XML/PDF labels; no independent geometry rerender.",
            "exporter_status": "External XML-derived pipeline; no checked-in export script."}


def verify_fig1_provenance():
    qa = json.loads(FIG1_QA.read_text(encoding="utf-8"))
    if qa.get("generator_sha256") != sha256(FIG1_GENERATOR):
        raise ValueError("Figure 1 generator hash mismatch; rerun publication/make_fig1.py")
    suffixes = {"pdf": ".pdf", "svg": ".svg", "png": ".png", "grayscale_png": "-grayscale.png"}
    for kind, suffix in suffixes.items():
        path = OUT / f"publication/fig1-supervisory-binding{suffix}"
        if qa.get("sha256", {}).get(kind) != sha256(path):
            raise ValueError(f"Figure 1 output hash mismatch: {path.name}")
    if qa.get("preserved_reference_sha256") != sha256(OUT / "gpt/fig1-intro-tii.png"):
        raise ValueError("Figure 1 preserved reference hash mismatch")
    return {"generator_sha256": qa["generator_sha256"], "sha256": qa["sha256"],
            "context_snapshot_note": "Owner QA input_assets are historical editorial context, not current benchmark inputs."}


def verify_walkthrough_provenance():
    qa = json.loads(WALKTHROUGH_PROVENANCE.read_text(encoding="utf-8"))
    folder = OUT / "walkthrough"
    source = folder / "aw_working-source.png"
    if qa.get("source") != source.name or qa.get("source_sha256") != sha256(source):
        raise ValueError("Walkthrough original screenshot hash mismatch")
    if qa.get("output_pdf_sha256") != sha256(folder / "fig-operational-walkthrough.pdf"):
        raise ValueError("Walkthrough output PDF hash mismatch")
    with Image.open(source) as original:
        original = original.convert("RGB")
        if list(original.size) != qa.get("original_size") or len(qa.get("panels", [])) != 4:
            raise ValueError("Walkthrough screenshot dimensions/panels do not match provenance")
        for index, panel in enumerate(qa["panels"], 1):
            crop = folder / f"ui-crop-{index}.png"
            if (panel.get("panel") != index or panel.get("source_ui_pixels_modified") is not False
                    or panel.get("crop_sha256") != sha256(crop)):
                raise ValueError(f"Walkthrough crop hash/provenance mismatch: {crop.name}")
            with Image.open(crop) as actual:
                expected = original.crop(panel["crop_xyxy"])
                if actual.size != expected.size or actual.convert("RGB").tobytes() != expected.tobytes():
                    raise ValueError(f"Walkthrough crop pixels differ from original: {crop.name}")
    return {"source_sha256": qa["source_sha256"], "output_pdf_sha256": qa["output_pdf_sha256"],
            "original_crop_pixels_verified": True,
            "scope": "The supplied screenshot itself is the original crop source; no upstream screenshot is required."}


def print_fig3_export_instructions():
    print("Figure 3 export is intentionally not implicit: no checked-in exporter exists.")
    print("1. Coordinate with the Figure 3 owner; freeze and hash the current XML before export:")
    print(f"   source: {FIG3_SOURCE}")
    print("2. Use that owner's XML-derived pipeline (geometry, parent offsets, fonts, source/target anchors and bends).")
    print("   Export PDF, SVG and PNG from the same XML; PDF must be 7.16 x 3.50 in, vector-only, with embedded fonts and >=8 pt annotations.")
    print(f"   output: {FIG3_OUTPUT}")
    print("3. Write the owner's *-qa.json receipt with files[].submission/sha256 for XML, PDF, SVG and PNG;")
    print("   include xml_native_cells, native_connectors, pdf_raster_images and minimum_pdf_font_pt (icon slots are checked from XML).")
    print("   Recheck that the XML did not change during export. Do not reuse the retired channel-loop layout.")
    print("4. Refresh only aggregate metadata after all owners finish:")
    print("   python paper/tii/SUBMISSION-IEEE-TII/figures/make_publication_figures.py --verify-only --refresh-metadata")


def _run_fig1_generator():
    runpy.run_path(str(FIG1_GENERATOR), run_name="__main__")


def _protected_binary_hashes(allowed):
    return {
        path.relative_to(OUT).as_posix(): sha256(path)
        for path in OUT.rglob("*")
        if path.is_file() and path.suffix.lower() in {".pdf", ".png", ".svg", ".drawio"}
        and path not in allowed
    }


def input_hashes():
    """Inputs and owner scripts are read-only even during ordinary generation."""
    files = [ROOT / name for name in SOURCES]
    files += [ROOT / FIG3_SOURCE, OUT / "drawio/fig2-architecture.drawio",
              OUT / "gpt/fig1-intro-tii.png", OUT / "walkthrough/aw_working-source.png",
              FIG1_GENERATOR, OUT / "walkthrough/make_walkthrough.py",
              Path(__file__).resolve(), OUT / "make_tii_figures.py"]
    return {path.relative_to(ROOT).as_posix(): sha256(path) for path in files}


def verify_preserved_assets():
    for name, expected in PRESERVED_ASSETS.items():
        if sha256(OUT / name) != expected:
            raise ValueError(f"Preserved architecture asset hash mismatch: {name}")


def _write_metadata(env, mission, qa, provenance, protected):
    """Refresh only the three aggregate JSON files after verifying all owners."""
    prefix = OUT.relative_to(ROOT).as_posix()
    source_lists = {
        "fig1-supervisory-binding": [f"{prefix}/publication/make_fig1.py", f"{prefix}/gpt/fig1-intro-tii.png"],
        "fig2-architecture": [f"{prefix}/drawio/fig2-architecture.drawio"],
        "fig3-governed-supervisory-workflow": [FIG3_SOURCE],
        "fig-operational-walkthrough": [f"{prefix}/walkthrough/aw_working-source.png"],
        "fig-agentteam-mission": list(SOURCES),
    }
    figure_generators = {
        "fig1-supervisory-binding": "publication/make_fig1.py",
        "fig2-architecture": None,
        "fig3-governed-supervisory-workflow": None,
        "fig-operational-walkthrough": "walkthrough/make_walkthrough.py",
        "fig-agentteam-mission": "make_publication_figures.py",
    }
    ownership = {
        "fig1-supervisory-binding": "Figure 1 owner; orchestrator delegates to its scoped generator.",
        "fig2-architecture": "Preserved existing architecture; never regenerated by this entry point.",
        "fig3-governed-supervisory-workflow": "Figure 3 owner; XML and all exports are read-only to this entry point.",
        "fig-operational-walkthrough": "Parent/walkthrough owner; source screenshot, crops and outputs are read-only here.",
        "fig-agentteam-mission": "Publication orchestrator; only in-module renderer, using frozen B exactly.",
    }
    dependencies = {
        "fig1-supervisory-binding": ["Python", "matplotlib", "numpy", "PyMuPDF", "Times New Roman"],
        "fig2-architecture": ["Preserved Chromium/Skia PDF; embedded Calibri"],
        "fig3-governed-supervisory-workflow": ["External XML-derived renderer (not checked in)", "matplotlib", "Times New Roman"],
        "fig-operational-walkthrough": ["Python", "matplotlib", "numpy", "Pillow", "PyMuPDF", "Times New Roman"],
        "fig-agentteam-mission": ["Python", "matplotlib", "numpy", "PyMuPDF", "Times New Roman"],
    }
    outputs = {relative: sha256(OUT / relative)
               for name, (pdf, _) in FIGURES.items() for relative in [pdf, *EXTRA_OUTPUTS[name]]}
    generators = {name: sha256(OUT / name) for name in
                  ("make_publication_figures.py", "make_tii_figures.py",
                   "publication/make_fig1.py", "walkthrough/make_walkthrough.py")}
    receipts = {path.relative_to(OUT).as_posix(): sha256(path)
                for path in (FIG1_QA, FIG3_QA, WALKTHROUGH_PROVENANCE)}
    source_hashes = {name: sha256(ROOT / name) for names in source_lists.values() for name in names}
    plotted = {
        "archive": ARCHIVE, "seed": env["seed"], "git_commit": env["gitCommit"],
        "harness_hash": env["harnessHash"], "node": env["node"], "mission": mission,
        "objective_um": {"target": 25.0, "tolerance": 0.7,
                         "source": f"bench/results/{ARCHIVE}/agentteam-biax.log:9"},
        "ledger_labels": {k: {"parameter": v[0], "unit": v[1], "transport": v[2]}
                          for k, v in KNOBS.items()},
        "display": {"setpoint_decimal_places": 1, "thickness_decimal_places": 2,
                    "x": "archived intervention index, not elapsed time", "connecting_lines": False},
        "scope": "Frozen B only; simulated plant, scripted policy; no interpolation or data edits.",
        "current_figures": list(FIGURES),
        "schematics": "Figures 1-3 are conceptual diagrams, not measured series or empirical comparisons.",
        "current_figure3": {"source": FIG3_SOURCE, **provenance["fig3-governed-supervisory-workflow"]},
        "walkthrough": {"source": source_lists["fig-operational-walkthrough"][0],
                        "scope": "Authentic running-software screenshot crops, not an additional benchmark trial."},
    }
    policy = {"raster_allowed_only_for": ["fig-operational-walkthrough"],
              "minimum_annotation_font_pt": 8, "embedded_fonts_required": True,
              "screenshot_policy": "Original screenshot crop pixels are preserved; minimum font size applies only to added vector annotations."}
    qa_document = {
        "schema_version": 2, "automated_checks": "pass", "figures": qa,
        "current_manuscript_figures": list(FIGURES), "output_policy": policy,
        "frozen_B_unchanged": True, "source_immutability_checked": True,
        "protected_asset_hashes": protected, "provenance": provenance,
        "visual_inspection": "Owner-specific reviews remain in their hash-linked QA receipts. Aggregate checks are not independent visual approval.",
        "learnings": ["Keep the categorical mission index unconnected; no timestamps or raw buckets are archived.",
                      "Keep full archived floating-point values in plotted-data.json; round only figure labels.",
                      "Never regenerate Figures 1 or 3 from the retired aggregate layouts.",
                      "Walkthrough source UI pixels are genuine screenshot crops, not vector annotation text."],
    }
    # Serialize once: the manifest hashes the exact bytes written to the owned QA/data files.
    plotted_bytes = (json.dumps(plotted, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    qa_bytes = (json.dumps(qa_document, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    manifest = {
        "schema_version": 2,
        "figures": {name: {"manuscript_asset": pdf, "owner": ownership[name],
                            "generator": figure_generators[name], "renderer_dependencies": dependencies[name],
                            "sources": source_lists[name], "outputs": [pdf, *EXTRA_OUTPUTS[name]],
                            "qa": qa[name]}
                    for name, (pdf, _) in FIGURES.items()},
        "figure_sizes_inches": {name: list(size) for name, (_, size) in FIGURES.items()},
        "renderer_versions": {"python": platform.python_version(), "matplotlib": matplotlib.__version__,
                              "numpy": np.__version__, "pillow": pillow_version, "pymupdf": fitz.VersionBind},
        "source_hashes": source_hashes, "source_path_base": "repository root",
        "figure_sources": source_lists, "figure_source_path_base": "repository root",
        "outputs": outputs, "output_path_base": "this manifest's directory",
        "generator_hashes": generators, "generator_path_base": "this manifest's directory",
        "provenance_hashes": receipts, "provenance_path_base": "this manifest's directory",
        "plotted_data_sha256": hashlib.sha256(plotted_bytes).hexdigest(),
        "figure_qa_sha256": hashlib.sha256(qa_bytes).hexdigest(),
        "output_policy": policy,
        "fig3_export": provenance["fig3-governed-supervisory-workflow"],
        "architecture_provenance": "Source and PDF preserved with fixed hashes; historical export script is unavailable. No fresh XML/PDF derivation claimed.",
        "reproduce": f"python {prefix}/make_publication_figures.py",
        "refresh_metadata": f"python {prefix}/make_publication_figures.py --refresh-metadata",
        "verify": f"python {prefix}/make_publication_figures.py --verify-only",
        "fig3_export_instructions": f"python {prefix}/make_publication_figures.py --export-fig3",
        "walkthrough_reproduce": f"python {prefix}/walkthrough/make_walkthrough.py (parent-owned; run separately after coordination)",
        "compatibility_command": f"python {prefix}/make_tii_figures.py",
        "scope": "Five current manuscript figures, all rendered outputs and owner receipts hashed; unreferenced legacy binaries retained untouched.",
    }
    (OUT / "plotted-data.json").write_bytes(plotted_bytes)
    (OUT / "figure-qa.json").write_bytes(qa_bytes)
    (OUT / "source-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def verify_metadata():
    manifest = json.loads((OUT / "source-manifest.json").read_text(encoding="utf-8"))
    expected_outputs = {relative for name, (pdf, _) in FIGURES.items() for relative in [pdf, *EXTRA_OUTPUTS[name]]}
    if (manifest.get("schema_version") != 2 or set(manifest.get("figures", {})) != set(FIGURES)
            or set(manifest.get("outputs", {})) != expected_outputs):
        raise ValueError("Aggregate metadata does not describe the current five figures; use --refresh-metadata")
    for field, base in (("outputs", OUT), ("source_hashes", ROOT), ("generator_hashes", OUT), ("provenance_hashes", OUT)):
        for name, digest in manifest[field].items():
            if sha256(base / name) != digest:
                raise ValueError(f"Metadata hash mismatch in {field}: {name}; use --refresh-metadata after owner completion")
    for filename, field in (("plotted-data.json", "plotted_data_sha256"), ("figure-qa.json", "figure_qa_sha256")):
        if sha256(OUT / filename) != manifest[field]:
            raise ValueError(f"Metadata hash mismatch: {filename}")
    qa = json.loads((OUT / "figure-qa.json").read_text(encoding="utf-8"))
    for name, digest in qa["protected_asset_hashes"].items():
        if sha256(OUT / name) != digest:
            raise ValueError(f"Protected asset hash mismatch: {name}")
    _, mission = load_mission()
    if json.loads((OUT / "plotted-data.json").read_text(encoding="utf-8"))["mission"] != mission:
        raise ValueError("Plotted mission data differs from frozen B")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--skip-fig1", action="store_true", help="preserve Figure 1; regenerate only the mission")
    parser.add_argument("--verify-only", action="store_true", help="read-only verification of all five assets and stored metadata")
    parser.add_argument("--refresh-metadata", action="store_true", help="validate all five existing assets and refresh ONLY aggregate JSON metadata; no figure generators")
    parser.add_argument("--export-fig3", action="store_true", help="print explicit owner/export/receipt instructions; do not render or write")
    args = parser.parse_args(argv)
    if args.export_fig3:
        print_fig3_export_instructions()
        return 0

    regenerate = not (args.verify_only or args.refresh_metadata)
    allowed = (set() if not regenerate else MISSION_OUTPUTS | (set() if args.skip_fig1 else FIG1_OUTPUTS))
    before_inputs = input_hashes()
    before_assets = _protected_binary_hashes(allowed)
    before_receipts = {path: sha256(path) for path in (FIG3_QA, WALKTHROUGH_PROVENANCE)}
    if not regenerate or args.skip_fig1:
        before_receipts[FIG1_QA] = sha256(FIG1_QA)
    try:
        # Preflight read-only sources and externally owned exports before any generator writes.
        env, mission = load_mission()
        verify_preserved_assets()
        provenance = {"fig3-governed-supervisory-workflow": verify_fig3_provenance(),
                      "fig-operational-walkthrough": verify_walkthrough_provenance()}
        if regenerate:
            configure()
            if not args.skip_fig1:
                _run_fig1_generator()
            save_and_check(mission_figure(mission), "fig-agentteam-mission")
        provenance["fig1-supervisory-binding"] = verify_fig1_provenance()
        qa = {name: check_pdf(name) for name in FIGURES}
    finally:
        if before_inputs != input_hashes():
            raise ValueError("A read-only source or generator changed during the run; coordinate with its owner and retry")
        if before_assets != _protected_binary_hashes(allowed):
            raise ValueError("A protected current or legacy figure asset changed during the run")
        if any(sha256(path) != digest for path, digest in before_receipts.items()):
            raise ValueError("An owner provenance receipt changed during verification; retry after owner completion")
    if regenerate or args.refresh_metadata:
        _write_metadata(env, mission, qa, provenance, _protected_binary_hashes(FIG1_OUTPUTS | MISSION_OUTPUTS))
    verify_metadata()
    print(f"PASS: five current figures; frozen B {ARCHIVE}; all source/generator/output hashes verified")
    print("  Generated scoped Figure 1/mission only." if regenerate else "  No figure scripts or outputs modified.")
    for name, info in qa.items():
        print(f"  {name}: {info['size_in']} in; minimum annotation {info['minimum_annotation_font_pt']} pt; "
              f"embedded fonts; raster images={info['raster_images_in_pdf']}")
    if args.refresh_metadata:
        print("  Refreshed source-manifest.json, figure-qa.json and plotted-data.json only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
