/** 调试 dcw-controller 可用性 */
const { getDcwLineRepo } = await import('../server/services/workshop/dcw/dcw-line.repo')
const line = getDcwLineRepo().create({ name: 'debug-line' })
console.log('line:', line.id)
const { getDcwController } = await import('../server/services/workshop/dcw/dcw-controller')
console.log('controller loaded')
const ctrl = getDcwController()
console.log('ctrl got')
const node = ctrl.create({ templateRef: 'dcw-temp-sp', name: 'debug-sp', driver: 'mock', lineId: line.id, min: 150, max: 200, unit: '℃' })
console.log('node:', node.id)
